# Generated by Django 3.1.4 on 2021-01-20 03:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Latest_Board', models.TextField(default='rnbqkbnr/pppppppp/8/8/8/8/PPPPPPPP/RNBQKBNR w KQkq - 0 1')),
            ],
        ),
        migrations.CreateModel(
            name='Move',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Latest_Move', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('Email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('Date_Joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('Password', models.TextField(default='')),
            ],
        ),
    ]
