# Generated by Django 3.1.4 on 2021-01-20 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chessapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Username',
            field=models.TextField(default=''),
        ),
    ]
